apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: opsbridge-manifests
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kallol08/opsbridge-suite-source